server:
  port: 8080

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka
  instance:
    instance-id: zuul-server
    prefer-ip-address: true

zuul:
  #设置统一前缀
  prefix: /myzuul
  #启用debug
  debug:
    request: true
  routes:
    eureka-client:
      path: /client/**
      serviceId: eureka-client
      sensitive-headers: Cookie,Set-Cookie #http header 中的敏感信息，默认情况下，ZUUL 是不转发的, OAuth2 的鉴权信息是放在 Authorization 中，所以需要从配置中移除
  host:
    # 配置zuul的超时时间,默认2秒，
    connect-timeout-millis: 2000
    socket-timeout-millis: 2000
  retryable: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

# zuul使用服务发现的时候，要想让上面的配置生效，必须配置ribbon的超时时间
ribbon:
  # 请求处理时间
  ReadTimeout: 1000
  # 请求连接时间
  ConnectTimeout: 1000
  # 同一个服务的最大重试次数
  MaxAutoRetries: 1
  # 对于切换的下一个实例的重试次数
  MaxAutoRetriesNextServer: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9090/uaa/oauth/token #令牌端点
      user-authorization-uri: http://localhost:9090/uaa/oauth/authorize #授权端点
      client-id: zuul-server #OAuth2客户端ID
      client-secret: secret #OAuth2客户端密钥
    resource:
      jwt:
        key-value: springcloud123 #使用对称加密方式，默认算法为HS256
